### PR TITLE
Compile with old MinGW 7.0.0 (GCC 7.5.0)

### PR DESCRIPTION
**Pull request by guidol70**
Hi ,
after taking the [oldest 32Bit WinLabs MinGW](https://github.com/brechtsanders/winlibs_mingw/releases/download/7.5.0-7.0.0-r1/winlibs-i686-posix-dwarf-gcc-7.5.0-mingw-w64-7.0.0-r1.7z) or the [oldest 64Bit WinLabs MinGW](https://github.com/brechtsanders/winlibs_mingw/releases/download/7.5.0-7.0.0-r1/winlibs-x86_64-posix-seh-gcc-7.5.0-mingw-w64-7.0.0-r1.7z)
from their [website](https://github.com/brechtsanders/winlibs_mingw/releases?page=16) (all way down the page into the rabbit-hole)
I could compile your newest Basic2 (Basic 1.5a) with this MinGW 7.0.0 without errors :)
```
Filesystem started
Stefan's Basic 1.5a Memory 65535 1024
```

Before the additinal semicolons I did get an error about the const at line 85 - because (I think) the semicolons were missing.

and
```
runtime.c:1965:1: error: unknown type name 'int32_t'; did you mean 'uint
 int32_t devfasttick = 0;
 ^~~~~~~
 uint32_t
```

Please check.

This version need only to be unzipped (as extracted in a mingw32-folder) and then put there the extracted mingwvars.bat and execute it before the first compile from your source-directory ;)

[mingwvars.zip](https://github.com/slviajero/tinybasic/files/12598006/mingwvars.zip)

[Basic2_MinGW_compiled.zip](https://github.com/slviajero/tinybasic/files/12610860/Basic2_MinGW_compiled.zip)

Maybe this could help to rellace your old mingw 6.x you mentioned in the [Issue 50](https://github.com/slviajero/tinybasic/issues/50)

IoTBASIC_MinGW_Calc_Pi1000

Kind regards
Guido

### CODE REVIEW

**Comment by slviajero** [comment]
Fixed now directly.
